# Setup
title:        Lewis Lebentz
tagline:      Lewis Lebentz's Personal Website
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Lewis Lebentz
  url:        https://lew.im

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
