# Setup
title:        Lewis Lebentz
tagline:      Code, tech and cool stuff
baseurl:      ""
permalink:    /:year/:month/:title/
paginate:     5

# About/contact
author:
  name:       Lewis Lebentz
  url:        https://lew.im

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
