# Setup
title:        Lewis Lebentz
tagline:      Code, tech and cool stuff
baseurl:      ""
url:          https://lew.im
permalink:    /:year/:month/:title/
paginate:     5

# About/contact
author:
  name:       Lewis Lebentz
  url:        https://lew.im

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

#Others
markdown: kramdown
